
services:
  db:
    image: postgres:16
    container_name: platos_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: platos_backend
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data:
