# Dockerfile
FROM node:20-alpine

# Directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json para instalar dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install --production

# Copiar el resto del proyecto
COPY . .

# Compilar la app NestJS
RUN npm run build

# Exponer puerto de la app
EXPOSE 3000

# Comando para ejecutar la app
CMD ["node", "dist/main.js"]
